swagger: '2.0'
info:
  version: '0.1.0'
  title: Api Gamification
  description: An API to demonstrate Swagger
host: localhost:8080
basePath: /badge
schemes:
  - http
paths:
  /badge:
    post:
      description: create a badge
      operationId: createFruit
      consumes:
        - application/json
      parameters:
        - name: badge
          in: body
          required: true
          schema:
            $ref: '#/definitions/Badge'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all fruits
      operationId: getFruits
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'
definitions:
  Fruit:
    type: object
    properties:
      kind:
        type: string
      colour:
        type: string
      size:
        type: string