version : '2'

services :
  db:
    image: mysql:5.7
    container_name: amt_gamificationAPI_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: GamificationAPIDatabase
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdataAPI:/var/lib/mysql

  spring-boot:
    build: spring-boot
    container_name: amt_spring_boot
    depends_on: 
      - db
    ports :
      - "8080:8080"
    links:
      - db

volumes:
    dbdataAPI:
