version : '2'

services :
  db:
    image: mysql:5.7
    container_name: amt_gamificationAPI_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: GamificationAPIDatabase
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdataAPI:/var/lib/mysql

volumes:
    dbdataAPI:
