swagger: '2.0'
info:
  version: '0.1.0'
  title: Gametown API
  description: An API for Gamification
host: localhost:8080
basePath: /api
schemes:
- http
paths:
  /users:
    post:
      description: create a user
      operationId: createUser
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all users
      operationId: getUsers
      produces:
      - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /users/{userId}:
    get:
      description: get a user
      operationId: getUser
      produces:
      - application/json
      parameters:
      - in: path
        name: userId
        required: true
        type: integer
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/User'

  /users/{userId}/badges:
    post:
      description: create a badge
      operationId: createBadge
      consumes:
      - application/json
      parameters:
      - in: path
        name: userId
        required: true
        type: integer
      - name: badge
        in: body
        required: true
        schema:
          $ref: '#/definitions/Badge'
      responses:
        '201':
          description: created
          schema:
            type: object

    get:
      description: get a user's badge list
      operationId: getUserBadges
      produces:
      - application/json
      parameters:
      - in: path
        name: userId
        required: true
        type: integer
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Badge'

definitions:
  User:
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      badges:
        type: array
        items:
          $ref: '#/definitions/Badge'

  Badge:
    type: object
    properties:
      name:
        type: string
